# Generated by Django 3.0.3 on 2020-03-03 22:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Tag Name')),
                ('description', models.CharField(max_length=100, verbose_name='Tag Description')),
                ('src_data', models.TextField(blank=True, default=None, null=True)),
                ('dst_data', models.TextField(blank=True, default=None, null=True)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, verbose_name='Dashboard Integration Description')),
                ('baseurl', models.CharField(default='https://api.meraki.com/api/v0', max_length=64)),
                ('apikey', models.CharField(max_length=64)),
                ('orgid', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('raw_data', models.TextField(blank=True, default=None, null=True)),
                ('force_rebuild', models.BooleanField(default=False, verbose_name='Force Dashboard Sync')),
                ('skip_sync', models.BooleanField(default=False, editable=False)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_sync', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ISEMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ise_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ISEServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, verbose_name='ISE Server Description')),
                ('ipaddress', models.CharField(max_length=64)),
                ('username', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('password', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('raw_data', models.TextField(blank=True, default=None, null=True)),
                ('force_rebuild', models.BooleanField(default=False, verbose_name='Force Server Sync')),
                ('skip_sync', models.BooleanField(default=False, editable=False)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_sync', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Policy Name')),
                ('description', models.CharField(max_length=100, verbose_name='Policy Description')),
                ('src_data', models.TextField(blank=True, default=None, null=True)),
                ('dst_data', models.TextField(blank=True, default=None, null=True)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Tag Name')),
                ('description', models.CharField(max_length=100, verbose_name='Tag Description')),
                ('do_sync', models.BooleanField(default=False, verbose_name='Sync this Tag?')),
                ('tag_number', models.IntegerField(default=0)),
                ('src_data', models.TextField(blank=True, default=None, null=True)),
                ('dst_data', models.TextField(blank=True, default=None, null=True)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SyncSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, verbose_name='Sync Description')),
                ('ise_source', models.BooleanField(default=True, verbose_name='Is ISE Config base?')),
                ('dashboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sync.Dashboard')),
                ('isematrix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sync.ISEMatrix')),
                ('iseserver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sync.ISEServer')),
            ],
        ),
    ]
