# Generated by Django 3.0.3 on 2020-03-03 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syncsession',
            name='iseserver',
        ),
        migrations.AddField(
            model_name='isematrix',
            name='iseserver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sync.ISEServer'),
        ),
    ]
